import type { Track } from "../types";

export const LEVEL_2A_TRACKS: Track[] = [
    { id: 1, 
      name: "Unit 1 - What's that? It's ...", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "bear", image: "card1.png" },
      { id: 2, word: "panda", image: "card2.png" },
      { id: 3, word: "deer", image: "card3.png" },
      { id: 4, word: "zebra", image: "card4.png" },
      { id: 5, word: "kangaroo", image: "card5.png" },
      { id: 6, word: "giraffe", image: "card6.png" },
      { id: 7, word: "parrot", image: "card7.png" },
      { id: 8, word: "peacock", image: "card8.png" }
    ]
    },
    { id: 2, 
      name: "Unit 2 - It's ...", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "a toothbrush", image: "card1.png"},
      { id: 2, word: "a comb", image: "card2.png" },
      { id: 3, word: "a towel", image: "card3.png" },
      { id: 4, word: "soap", image: "card4.png" },
      { id: 5, word: "toothpaste", image: "card5.png" },
      { id: 6, word: "shampoo", image: "card6.png" },
      ]
    },
    { id: 3, 
      name: "Unit 3 - He's a ... She's a ...", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "a dwarf", image: "card1.png"},
      { id: 2, word: "a giant", image: "card2.png" },
      { id: 3, word: "a king", image: "card3.png" },
      { id: 4, word: "a prince", image: "card4.png" },
      { id: 5, word: "a pirate", image: "card5.png" },
      { id: 6, word: "a fairy", image: "card6.png" },
      { id: 7, word: "a queen", image: "card7.png" },
      { id: 8, word: "a princess", image: "card8.png" }
      ]
    },
    { id: 4, 
      name: "Unit 4 - Let's learn more.", 
      numFlashcards: 12,
      cards: [
      { id: 1, word: "big", image: "card1.png"},
      { id: 2, word: "small", image: "card2.png" },
      { id: 3, word: "long", image: "card3.png" },
      { id: 4, word: "short (pencil)", image: "card4.png" },
      { id: 5, word: "clean", image: "card5.png" },
      { id: 6, word: "dirty", image: "card6.png" },
      { id: 7, word: "old", image: "card7.png" },
      { id: 8, word: "young", image: "card8.png" },
      { id: 9, word: "tall", image: "card9.png" },
      { id: 10, word: "short (girl)", image: "card10.png" },
      { id: 11, word: "fat", image: "card11.png" },
      { id: 12, word: "thin", image: "card12.png" },
      ]
    },
    { id: 5, 
      name: "Unit 5 - It's ... They're ...", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "head", image: "card1.png"},
      { id: 2, word: "neck", image: "card2.png" },
      { id: 3, word: "tooth", image: "card3.png" },
      { id: 4, word: "arm", image: "card4.png" },
      { id: 5, word: "legs", image: "card5.png" },
      { id: 6, word: "knees", image: "card6.png" },
      { id: 7, word: "toes", image: "card7.png" },
      { id: 8, word: "fingers", image: "card8.png" },
      ]
    },
    { id: 6, 
      name: "Unit 6 - They're ...", 
      numFlashcards: 16,
      cards: [
      { id: 1, word: "a doctor", image: "card1.png"},
      { id: 2, word: "doctors", image: "card2.png" },
      { id: 3, word: "a nurse", image: "card3.png" },
      { id: 4, word: "nurses", image: "card4.png" },
      { id: 5, word: "a driver", image: "card5.png" },
      { id: 6, word: "drivers", image: "card6.png" },
      { id: 7, word: "a soldier", image: "card7.png" },
      { id: 8, word: "soldiers", image: "card8.png" },
      { id: 9, word: "a teacher", image: "card9.png" },
      { id: 10, word: "teachers", image: "card10.png" },
      { id: 11, word: "a student", image: "card11.png" },
      { id: 12, word: "students", image: "card12.png" },
      { id: 13, word: "a singer", image: "card13.png" },
      { id: 14, word: "singers", image: "card14.png" },
      { id: 15, word: "a police officer", image: "card15.png" },
      { id: 16, word: "police officers", image: "card16.png" },
      ]
    },
    { id: 7, 
      name: "Unit 7 - There's ...", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "an ant", image: "card1.png"},
      { id: 2, word: "a mosquito", image: "card2.png" },
      { id: 3, word: "a cockroach", image: "card3.png" },
      { id: 4, word: "a bee", image: "card4.png" },
      { id: 5, word: "a ladybug", image: "card5.png" },
      { id: 6, word: "a butterfly", image: "card6.png" },
      { id: 7, word: "a dragonfly", image: "card7.png" },
      ]
    },
    { id: 8, 
      name: "Unit 8 - Let's learn more", 
      numFlashcards: 3,
      cards: [
      { id: 1, word: "Blow your nose with tissue.", image: "card1.png"},
      { id: 2, word: "Cover your mouth with your hand.", image: "card2.png" },
      { id: 3, word: "Don't talk with your mouth full.", image: "card3.png" },
      ]
    },
    { id: 9, 
      name: "Unit 9 - Point to the ...", 
      numFlashcards: 7,
      cards: [
        { id: 1, word: "ceiling", image: "card1.png"},
        { id: 2, word: "clock", image: "card2.png" },
        { id: 3, word: "floor", image: "card3.png" },
        { id: 4, word: "wall", image: "card4.png" },
        { id: 5, word: "window", image: "card5.png" },
        { id: 6, word: "curtains", image: "card6.png" },
        { id: 7, word: "door", image: "card7.png" },
      ]
    },
    { id: 10, 
      name: "Unit 10 - Do you want some ...?", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "bread", image: "card1.png"},
      { id: 2, word: "congee", image: "card2.png" },
      { id: 3, word: "milk", image: "card3.png" },
      { id: 4, word: "hot dogs", image: "card4.png" },
      { id: 5, word: "dumplings", image: "card5.png" },
      { id: 6, word: "rice dumplings", image: "card6.png" },
      ]
    },
    { id: 11, 
      name: "Unit 11 - Which one do you want ... or ...?", 
      numFlashcards: 14,
      cards: [
      { id: 1, word: "jam", image: "card1.png"},
      { id: 2, word: "peanut butter", image: "card2.png" },
      { id: 3, word: "an egg", image: "card3.png" },
      { id: 4, word: "ham", image: "card4.png" },
      { id: 5, word: "a sandwich", image: "card5.png" },
      { id: 6, word: "salad", image: "card6.png" },
      { id: 7, word: "a lollipop", image: "card7.png" },
      { id: 8, word: "chocolate", image: "card8.png" },
      { id: 9, word: "a cookie", image: "card9.png" },
      { id: 10, word: "potato chips", image: "card10.png" },
      { id: 11, word: "pudding", image: "card11.png" },
      { id: 12, word: "yogurt", image: "card12.png" },
      { id: 13, word: "tea", image: "card13.png" },
      { id: 14, word: "coffee", image: "card14.png" },
      ]
    },
    { id: 12, 
      name: "Unit 12 - Let's learn more.", 
      numFlashcards: 30,
      cards: [
      { id: 1, word: "one", image: "card1.png"},
      { id: 2, word: "two", image: "card2.png" },
      { id: 3, word: "three", image: "card3.png" },
      { id: 4, word: "four", image: "card4.png" },
      { id: 5, word: "five", image: "card5.png" },
      { id: 6, word: "six", image: "card6.png" },
      { id: 7, word: "seven", image: "card7.png" },
      { id: 8, word: "eight", image: "card8.png" },
      { id: 9, word: "nine", image: "card9.png" },
      { id: 10, word: "ten", image: "card10.png" },
      { id: 11, word: "eleven", image: "card11.png" },
      { id: 12, word: "twelve", image: "card12.png" },
      { id: 13, word: "thirteen", image: "card13.png" },
      { id: 14, word: "fourteen", image: "card14.png" },
      { id: 15, word: "fifteen", image: "card15.png" },
      { id: 16, word: "sixteen", image: "card16.png" },
      { id: 17, word: "seventeen", image: "card17.png" },
      { id: 18, word: "eighteen", image: "card18.png" },
      { id: 19, word: "nineteen", image: "card19.png" },
      { id: 20, word: "twenty", image: "card20.png" }, 
      { id: 21, word: "twenty-one", image: "card21.png" },
      { id: 22, word: "twenty-two", image: "card22.png" },
      { id: 23, word: "twenty-three", image: "card23.png" },
      { id: 24, word: "twenty-four", image: "card24.png" },
      { id: 25, word: "twenty-five", image: "card25.png" },
      { id: 26, word: "twenty-six", image: "card26.png" },
      { id: 27, word: "twenty-seven", image: "card27.png" },
      { id: 28, word: "twenty-eight", image: "card28.png" },
      { id: 29, word: "twenty-nine", image: "card29.png" },
      { id: 30, word: "thirty", image: "card30.png" },
      ]
    },
    { id: 13, 
      name: "Unit 13 - Where are you ? I'm in the ...", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "living room", image: "card1.png"},
      { id: 2, word: "bedroom", image: "card2.png" },
      { id: 3, word: "bathroom", image: "card3.png" },
      { id: 4, word: "kitchen", image: "card4.png" },
      { id: 5, word: "study", image: "card5.png" },
      { id: 6, word: "dining room", image: "card6.png" },
      ]
    },
    { id: 14, 
      name: "Unit 14 - I can ", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "kiss", image: "card1.png"},
      { id: 2, word: "hug", image: "card2.png" },
      { id: 3, word: "write ABC", image: "card3.png" },
      { id: 4, word: "stack blocks", image: "card4.png" },
      { id: 5, word: "play with a hula hoop", image: "card5.png" },
      { id: 6, word: "skip", image: "card6.png" },
      { id: 7, word: "Take out the book.", image: "card7.png" },
      { id: 8, word: "Put away the book.", image: "card8.png" },
      ]
    },
    { id: 15, 
      name: "Unit 15 - He can ... She can ...", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "kick a ball", image: "card1.png"},
      { id: 2, word: "lift a chair", image: "card2.png" },
      { id: 3, word: "ride a bike", image: "card3.png" },
      { id: 4, word: "fly a kite", image: "card4.png" },
      { id: 5, word: "find a toy", image: "card5.png" },
      { id: 6, word: "carry a bag", image: "card6.png" },
      { id: 7, word: "Pick up the marker.", image: "card7.png" },
      { id: 8, word: "Put down the marker.", image: "card8.png" },
      ]
    },
    { id: 16, 
      name: "Unit 16 - Let's learn more.", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "Monday", image: "card1.png"},
      { id: 2, word: "Tuesday", image: "card2.png" },
      { id: 3, word: "Wednesday", image: "card3.png" },
      { id: 4, word: "Thursday", image: "card4.png" },
      { id: 5, word: "Friday", image: "card5.png" },
      { id: 6, word: "Saturday", image: "card6.png" },
      { id: 7, word: "Sunday", image: "card7.png" },

      ]
    },
  ];
