import type { Track } from "../types";

export const LEVEL_2B_TRACKS: Track[] = [
    { id: 1, 
      name: "Unit 1 - I want ...", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "toy car", image: "card1.png" },
      { id: 2, word: "toy dinosaur", image: "card2.png" },
      { id: 3, word: "toy airplane", image: "card3.png" },
      { id: 4, word: "puppet", image: "card4.png" },
      { id: 5, word: "rings", image: "card5.png" },
      { id: 6, word: "playhouse", image: "card6.png" },
      { id: 7, word: "picture book", image: "card7.png" },
    ]
    },
    { id: 2, 
      name: "Unit 2 - What is it?", 
      numFlashcards: 8,
      cards: [
        { id: 1, word: "a shell", image: "card1.png"},
        { id: 2, word: "a dolphin", image: "card2.png" },
        { id: 3, word: "a starfish", image: "card3.png" },
        { id: 4, word: "a jellyfish", image: "card4.png" },
        { id: 5, word: "a whale", image: "card5.png" },
        { id: 6, word: "a stingray", image: "card6.png" },
        { id: 7, word: "a shark", image: "card7.png" },
        { id: 8, word: "an octopus", image: "card8.png" },
      ]
    },
    { id: 3, 
      name: "Unit 3 - What is it?  What are they?", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "a cherry", image: "card1.png"},
      { id: 2, word: "a strawberry", image: "card2.png" },
      { id: 3, word: "a bellfruit", image: "card3.png" },
      { id: 4, word: "a starfruit", image: "card4.png" },
      { id: 5, word: "a pear", image: "card5.png" },
      { id: 6, word: "a peach", image: "card6.png" },
      { id: 7, word: "an orange", image: "card7.png" },
      { id: 8, word: "grapes", image: "card8.png" },
      ]
    },
    { id: 4, 
      name: "Unit 4 - Let's learn more.", 
      numFlashcards: 3,
      cards: [
      { id: 1, word: "a doughnut", image: "card1.png"},
      { id: 2, word: "sushi", image: "card2.png" },
      { id: 3, word: "spaghetti", image: "card3.png" },
      ]
    },
    { id: 5, 
      name: "Unit 5 - What's the matter? I ...", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "a cold", image: "card1.png"},
      { id: 2, word: "a cough", image: "card2.png" },
      { id: 3, word: "a headache", image: "card3.png" },
      { id: 4, word: "a toothache", image: "card4.png" },
      { id: 5, word: "a stomachache", image: "card5.png" },
      { id: 6, word: "a runny nose", image: "card6.png" },
      { id: 7, word: "a sore throat", image: "card7.png" },
      { id: 8, word: "a fever", image: "card8.png" },
      ]
    },
    { id: 6, 
      name: "Unit 6 - Do you have ... ? May I borrow ...?", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "stamp", image: "card1.png"},
      { id: 2, word: "pencil case", image: "card2.png" },
      { id: 3, word: "stickers", image: "card3.png" },
      { id: 4, word: "money", image: "card4.png" },
      { id: 5, word: "glue", image: "card5.png" },
      { id: 6, word: "paintbrush", image: "card6.png" },
      { id: 7, word: "pencil sharpener", image: "card7.png" },
      { id: 8, word: "scissors", image: "card8.png" },
      ]
    },
    { id: 7, 
      name: "Unit 7 - Does he like ...? Does she like ...?", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "carrots", image: "card1.png"},
      { id: 2, word: "onions", image: "card2.png" },
      { id: 3, word: "potatoes", image: "card3.png" },
      { id: 4, word: "cabbage", image: "card4.png" },
      { id: 5, word: "corn", image: "card5.png" },
      { id: 6, word: "broccoli", image: "card6.png" },
      { id: 7, word: "cauliflower", image: "card7.png" },
      ]
    },
    { id: 8, 
      name: "Unit 8 - Let's learn more.", 
      numFlashcards: 8,
      cards: [
        { id: 1, word: "Mother's Day", image: "card1.png"},
        { id: 2, word: "Father's Day", image: "card2.png" },
        { id: 3, word: "Teacher's Day", image: "card3.png" },
        { id: 4, word: "Christmas", image: "card4.png" },
        { id: 5, word: "Dragon Boat Festival", image: "card5.png" },
        { id: 6, word: "Moon Festival", image: "card6.png" },
        { id: 7, word: "New Year", image: "card7.png" },
        { id: 8, word: "Chinese New Year", image: "card8.png" },
      ]
    },
    { id: 9, 
      name: "Unit 9 - Do you like to play ...?", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "basketball", image: "card1.png"},
      { id: 2, word: "baseball", image: "card2.png" },
      { id: 3, word: "table tennis", image: "card3.png" },
      { id: 4, word: "soccer", image: "card4.png" },
      { id: 5, word: "badminton", image: "card5.png" },
      { id: 6, word: "walk a dog", image: "card6.png" },
      ]
    },
    { id: 10, 
      name: "Unit 10 - What do you want to be? I want to be ...", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "a chef", image: "card1.png"},
      { id: 2, word: "a dentist", image: "card2.png" },
      { id: 3, word: "a fire fighter", image: "card3.png" },
      { id: 4, word: "a mail carrier", image: "card4.png" },
      { id: 5, word: "a clerk", image: "card5.png" },
      { id: 6, word: "a businessman", image: "card6.png" },
      { id: 7, word: "a pilot", image: "card7.png" },
      { id: 8, word: "an astronaut", image: "card8.png" },
      ]
    },
    { id: 11, 
      name: "Unit 11 - When do you have ...?", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "English class", image: "card1.png"},
      { id: 2, word: "Chinese class", image: "card2.png" },
      { id: 3, word: "math class", image: "card3.png" },
      { id: 4, word: "music class", image: "card4.png" },
      { id: 5, word: "swimming class", image: "card5.png" },
      { id: 6, word: "art class", image: "card6.png" },
      { id: 7, word: "computer class", image: "card7.png" },
      ]
    },
    { id: 12, 
      name: "Unit 12 - Let's learn more.", 
      numFlashcards: 3,
      cards: [
      { id: 1, word: "have breakfast", image: "card1.png"},
      { id: 2, word: "have lunch", image: "card2.png" },
      { id: 3, word: "have dinner", image: "card3.png" },

      ]
    },
    { id: 13, 
      name: "Unit 13 - What do you do every day? I ... every day.", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "get up", image: "card1.png"},
      { id: 2, word: "go to school", image: "card2.png" },
      { id: 3, word: "take a bath", image: "card3.png" },
      { id: 4, word: "brush my teeth", image: "card4.png" },
      { id: 5, word: "comb my hair", image: "card5.png" },
      { id: 6, word: "wash my face", image: "card6.png" },

      ]
    },
    { id: 14, 
      name: "Unit 14 - Where's the ...? It's in the ...", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "TV", image: "card1.png"},
      { id: 2, word: "air conditioner", image: "card2.png" },
      { id: 3, word: "telephone", image: "card3.png" },
      { id: 4, word: "bookcase", image: "card4.png" },
      { id: 5, word: "fan", image: "card5.png" },
      { id: 6, word: "fridge", image: "card6.png" },
      { id: 7, word: "mirror", image: "card7.png" },
      { id: 8, word: "keys", image: "card8.png" },

      ]
    },
    { id: 15, 
      name: "Unit 15 - Where are you going? I'm going to ...", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "zoo", image: "card1.png"},
      { id: 2, word: "beach", image: "card2.png" },
      { id: 3, word: "restaurant", image: "card3.png" },
      { id: 4, word: "bookstore", image: "card4.png" },
      { id: 5, word: "convenience store", image: "card5.png" },
      { id: 6, word: "toy store", image: "card6.png" },
      { id: 7, word: "department store", image: "card7.png" },
      ]
    },
    { id: 16, 
      name: "Unit 16 - Let's learn more.", 
      numFlashcards: 3,
      cards: [
      { id: 1, word: "police station", image: "card1.png"},
      { id: 2, word: "post office", image: "card2.png" },
      { id: 3, word: "hospital", image: "card3.png" },
      ]
    },
  ];
