import type { Track } from "../types";

export const LEVEL_3A_TRACKS: Track[] = [
    { id: 1, 
      name: "Unit 1 - It's ... It has ...", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "a camel", image: "card1.png" },
      { id: 2, word: "an alligator", image: "card2.png" },
      { id: 3, word: "a frog", image: "card3.png" },
      { id: 4, word: "a rhino", image: "card4.png" },
      { id: 5, word: "a gorilla", image: "card5.png" },
      { id: 6, word: "an ostrich", image: "card6.png" },
      { id: 7, word: "a snake", image: "card7.png" }
    ]
    },
    { id: 2, 
      name: "Unit 2 - There's a ...", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "bakery", image: "card1.png"},
      { id: 2, word: "drugstore", image: "card2.png" },
      { id: 3, word: "library", image: "card3.png" },
      { id: 4, word: "movie theater", image: "card4.png" },
      { id: 5, word: "gas station", image: "card5.png" },
      { id: 6, word: "swimming pool", image: "card6.png" },
      ]
    },
    { id: 3, 
      name: "Unit 3 - I have ... I can ...", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "a rag", image: "card1.png"},
      { id: 2, word: "a broom", image: "card2.png" },
      { id: 3, word: "a mop", image: "card3.png" },
      { id: 4, word: "a camera", image: "card4.png" },
      { id: 5, word: "a knife", image: "card5.png" },
      { id: 6, word: "chopsticks", image: "card6.png" }
      ]
    },
    { id: 4, 
      name: "Unit 4 - Let's learn more.", 
      numFlashcards: 5,
      cards: [
      { id: 1, word: "Moon Rabbit", image: "card1.png"},
      { id: 2, word: "Moon Lady", image: "card2.png" },
      { id: 3, word: "moon cakes", image: "card3.png" },
      { id: 4, word: "pomelo", image: "card4.png" },
      { id: 5, word: "barbecue", image: "card5.png" },
      ]
    },
    { id: 5, 
      name: "Unit 5 - I can play the ...", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "drum", image: "card1.png"},
      { id: 2, word: "tambourine", image: "card2.png" },
      { id: 3, word: "triangle", image: "card3.png" },
      { id: 4, word: "xylophone", image: "card4.png" },
      { id: 5, word: "recorder", image: "card5.png" },
      { id: 6, word: "violin", image: "card6.png" },
      { id: 7, word: "piano", image: "card7.png" },
      { id: 8, word: "guitar", image: "card8.png" },
      ]
    },
    { id: 6, 
      name: "Unit 6 - The ... is in / on / under ...", 
      numFlashcards: 4,
      cards: [
      { id: 1, word: "a mat", image: "card1.png"},
      { id: 2, word: "a switch", image: "card2.png" },
      { id: 3, word: "a box", image: "card3.png" },
      { id: 4, word: "a bed", image: "card4.png" }
      ]
    },
    { id: 7, 
      name: "Unit 7 - There's a ... in the ...", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "a sofa", image: "card1.png"},
      { id: 2, word: "a lamp", image: "card2.png" },
      { id: 3, word: "a closet", image: "card4.png" },
      { id: 5, word: "a CD player", image: "card5.png" },
      { id: 6, word: "an alarm clock", image: "card6.png" },
      ]
    },
    { id: 8, 
      name: "Unit 8 - Let's learn more", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "a pumpkin", image: "card1.png"},
      { id: 2, word: "a jack-o-lantern", image: "card2.png" },
      { id: 3, word: "a mask", image: "card3.png" },
      { id: 4, word: "a spider", image: "card4.png" },
      { id: 5, word: "a ghost", image: "card5.png" },
      { id: 6, word: "a bat", image: "card6.png" },
      { id: 7, word: "a witch", image: "card7.png" },
      { id: 8, word: "a vampire", image: "card8.png" },
      ]
    },
    { id: 9, 
      name: "Unit 9 - What's this?  What's that?", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "a microwave", image: "card1.png"},
      { id: 2, word: "a toaster", image: "card2.png" },
      { id: 3, word: "a blender", image: "card3.png" },
      { id: 4, word: "a toaster oven", image: "card4.png" },
      { id: 5, word: "a gas burner", image: "card5.png" },
      { id: 6, word: "a pot", image: "card6.png" },
      { id: 7, word: "a pan", image: "card7.png" },
      { id: 8, word: "a wok", image: "card8.png" },
      ]
    },
    { id: 10, 
      name: "Unit 10 - How do you say this/that in English?", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "a ticket", image: "card1.png"},
      { id: 2, word: "a balloon", image: "card2.png" },
      { id: 3, word: "popcorn", image: "card3.png" },
      { id: 4, word: "cotton candy", image: "card4.png" },
      { id: 5, word: "a carousel", image: "card5.png" },
      { id: 6, word: "a Ferris wheel", image: "card6.png" },
      { id: 7, word: "a roller coaster", image: "card7.png" },
      ]
    },
    { id: 11, 
      name: "Unit 11 - What do you want? I want...", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "bacon", image: "card1.png"},
      { id: 2, word: "sausage", image: "card2.png" },
      { id: 3, word: "cheese", image: "card3.png" },
      { id: 4, word: "seafood", image: "card4.png" },
      { id: 5, word: "tomatoes", image: "card5.png" },
      { id: 6, word: "mushrooms", image: "card6.png" },
      { id: 7, word: "eggplants", image: "card7.png" },
      { id: 8, word: "green peppers", image: "card8.png" },
      ]
    },
    { id: 12, 
      name: "Unit 12 - Let's learn more.", 
      numFlashcards: 10,
      cards: [
      { id: 1, word: "reindeer", image: "card1.png"},
      { id: 2, word: "Santa Claus", image: "card2.png" },
      { id: 3, word: "a Christmas tree", image: "card3.png" },
      { id: 4, word: "a gift", image: "card4.png" },
      { id: 5, word: "an angel", image: "card5.png" },
      { id: 6, word: "a snowman", image: "card6.png" },
      { id: 7, word: "a turkey", image: "card7.png" },
      { id: 8, word: "a candy cane", image: "card8.png" },
      { id: 9, word: "a wreath", image: "card9.png" },
      { id: 10, word: "a bell", image: "card10.png" },
      ]
    },
    { id: 13, 
      name: "Unit 13 - What do you do on the weekend?", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "do homework", image: "card1.png"},
      { id: 2, word: "play computer games", image: "card2.png" },
      { id: 3, word: "listen to music", image: "card3.png" },
      { id: 4, word: "go swimming", image: "card4.png" },
      { id: 5, word: "go shopping", image: "card5.png" },
      { id: 6, word: "go roller skating", image: "card6.png" },
      ]
    },
    { id: 14, 
      name: "Unit 14 - I can ... with my ... ", 
      numFlashcards: 17,
      cards: [
      { id: 1, word: "hear with my ears", image: "card1.png"},
      { id: 2, word: "see with my eyes", image: "card2.png" },
      { id: 3, word: "smell with my nose", image: "card3.png" },
      { id: 4, word: "touch with my hands", image: "card4.png" },
      { id: 5, word: "taste with my tongue", image: "card5.png" },
      { id: 6, word: "bird", image: "card6.png" },
      { id: 7, word: "cat", image: "card7.png" },
      { id: 8, word: "mosquito", image: "card8.png" },
      { id: 9, word: "the sun", image: "card9.png" },
      { id: 10, word: "the moon", image: "card10.png" },
      { id: 11, word: "the stars", image: "card11.png" },
      { id: 12, word: "bread", image: "card12.png" },
      { id: 13, word: "garlic", image: "card13.png" },
      { id: 14, word: "stone", image: "card14.png" },
      { id: 15, word: "snake", image: "card15.png" },
      { id: 16, word: "lollipops", image: "card16.png" },
      { id: 17, word: "lemons", image: "card17.png" },
      ]
    },
    { id: 15, 
      name: "Unit 15 - It's a ... They're ...", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "a coat", image: "card1.png"},
      { id: 2, word: "a scarf", image: "card2.png" },
      { id: 3, word: "a sweater", image: "card3.png" },
      { id: 4, word: "a vest", image: "card4.png" },
      { id: 5, word: "gloves", image: "card5.png" },
      { id: 6, word: "mittens", image: "card6.png" },
      { id: 7, word: "boots", image: "card7.png" },
      ]
    },
    { id: 16, 
      name: "Unit 16 - Let's learn more.", 
      numFlashcards: 18,
      cards: [
      { id: 1, word: "couplets", image: "card1.png"},
      { id: 2, word: "red envelope", image: "card2.png" },
      { id: 3, word: "lucky money", image: "card3.png" },
      { id: 4, word: "lion dance", image: "card4.png" },
      { id: 5, word: "dragon dance", image: "card5.png" },
      { id: 6, word: "firecrackers", image: "card6.png" },
      { id: 7, word: "reunion dinner", image: "card7.png" },
      { id: 8, word: "fish", image: "card8.png" },
      { id: 9, word: "hot pot", image: "card9.png" },
      { id: 10, word: "chicken", image: "card10.png" },
      { id: 11, word: "Chinese radish", image: "card11.png" },
      { id: 12, word: "rice cake", image: "card12.png" },
      { id: 13, word: "dumplings", image: "card13.png" },
      { id: 14, word: "tangerine", image: "card14.png" },
      { id: 15, word: "apple", image: "card15.png" },
      { id: 16, word: "pineapple", image: "card16.png" },
      { id: 17, word: "Don't cry.", image: "card17.png" },
      { id: 18, word: "Don't sweep the floor.", image: "card18.png" },
      ]
    },
  ];
