import type { Track } from "../types";

export const LEVEL_3B_TRACKS: Track[] = [
    { id: 1, 
      name: "Unit 1 - What time is it? It's...", 
      numFlashcards: 18,
      cards: [
      { id: 1, word: "1:00", image: "card1.png" },
      { id: 2, word: "2:00", image: "card2.png" },
      { id: 3, word: "3:00", image: "card3.png" },
      { id: 4, word: "4:00", image: "card4.png" },
      { id: 5, word: "5:00", image: "card5.png" },
      { id: 6, word: "6:00", image: "card6.png" },
      { id: 7, word: "7:00", image: "card7.png" },
      { id: 8, word: "8:00", image: "card8.png" },
      { id: 9, word: "9:00", image: "card9.png" },
      { id: 10, word: "10:00", image: "card10.png" },
      { id: 11, word: "11:00", image: "card11.png" },
      { id: 12, word: "12:00", image: "card12.png" },
      { id: 13, word: "get up", image: "card13.png" },
      { id: 14, word: "go to school", image: "card14.png" },
      { id: 15, word: "go home", image: "card15.png" },
      { id: 16, word: "have dinner", image: "card16.png" },
      { id: 17, word: "take a  bath", image: "card17.png" },
      { id: 18, word: "go to bed", image: "card18.png" }
    ]
    },
    { id: 2, 
      name: "Unit 2 - How much is it?  It's ... dollars.", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "stapler", image: "card1.png"},
      { id: 2, word: "folder", image: "card2.png" },
      { id: 3, word: "magazine", image: "card3.png" },
      { id: 4, word: "piggy bank", image: "card4.png" },
      { id: 5, word: "dictionary", image: "card5.png" },
      { id: 6, word: "music box", image: "card6.png" },
      ]
    },
    { id: 3, 
      name: "Unit 3 - What number is it?  It's ....", 
      numFlashcards: 10,
      cards: [
      { id: 1, word: "100", image: "card1.png"},
      { id: 2, word: "200", image: "card2.png" },
      { id: 3, word: "300", image: "card3.png" },
      { id: 4, word: "400", image: "card4.png" },
      { id: 5, word: "500", image: "card5.png" },
      { id: 6, word: "600", image: "card6.png" },
      { id: 7, word: "700", image: "card7.png" },
      { id: 8, word: "800", image: "card8.png" },
      { id: 9, word: "900", image: "card9.png" },
      { id: 10, word: "1000", image: "card10.png" },
      ]
    },
    { id: 4, 
      name: "Unit 4 - Let's learn more.", 
      numFlashcards: 5,
      cards: [
      { id: 1, word: "an Easter egg", image: "card1.png"},
      { id: 2, word: "the Easter bunny", image: "card2.png" },
      { id: 3, word: "chocolate bunny", image: "card3.png" },
      { id: 4, word: "Easter basket", image: "card4.png" },
      { id: 5, word: "hunt for eggs", image: "card5.png" },
      ]
    },
    { id: 5, 
      name: "Unit 5 - Where are you going? I'm going to ...", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "airport", image: "card1.png"},
      { id: 2, word: "museum", image: "card2.png" },
      { id: 3, word: "bank", image: "card3.png" },
      { id: 4, word: "florist", image: "card4.png" },
      { id: 5, word: "pet shop", image: "card5.png" },
      { id: 6, word: "train station", image: "card6.png" },
      { id: 7, word: "bus stop", image: "card7.png" },
      { id: 8, word: "night market", image: "card8.png" },
      ]
    },
    { id: 6, 
      name: "Unit 6 - Do you like ... / Does he like ...?", 
      numFlashcards: 8,
      cards: [
      { id: 1, word: "fish", image: "card1.png"},
      { id: 2, word: "crab", image: "card2.png" },
      { id: 3, word: "shrimp", image: "card3.png" },
      { id: 4, word: "squid", image: "card4.png" },
      { id: 5, word: "pork", image: "card5.png" },
      { id: 6, word: "beef", image: "card6.png" },
      { id: 7, word: "sweet potato", image: "card7.png" },
      { id: 8, word: "cucumber", image: "card8.png" },
      ]
    },
    { id: 7, 
      name: "Unit 7 - Can you pass me the ... ?", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "sugar", image: "card1.png"},
      { id: 2, word: "salt", image: "card2.png" },
      { id: 3, word: "pepper", image: "card3.png" },
      { id: 4, word: "honey", image: "card4.png" },
      { id: 5, word: "oil", image: "card5.png" },
      { id: 6, word: "ketchup", image: "card6.png" },
      { id: 7, word: "soy sauce", image: "card7.png" },
      ]
    },
    { id: 8, 
      name: "Unit 8 - Let's learn more", 
      numFlashcards: 2,
      cards: [
      { id: 1, word: "carnations", image: "card1.png"},
      { id: 2, word: "Mother's Day", image: "card2.png" },
      ]
    },
    { id: 9, 
      name: "Unit 9 - Do you want to ...?", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "play frisbee", image: "card1.png"},
      { id: 2, word: "play hopscotch", image: "card2.png" },
      { id: 3, word: "play hide and seek", image: "card3.png" },
      { id: 4, word: "blow bubbles", image: "card4.png" },
      { id: 5, word: "have a picnic", image: "card5.png" },
      { id: 6, word: "walk a dog", image: "card6.png" },
      ]
    },
    { id: 10, 
      name: "Unit 10 - Do you like ... / Does he like ...?", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "river", image: "card1.png"},
      { id: 2, word: "lake", image: "card2.png" },
      { id: 3, word: "rainbow", image: "card3.png" },
      { id: 4, word: "waterfall", image: "card4.png" },
      { id: 5, word: "grass", image: "card5.png" },
      { id: 6, word: "leaves", image: "card6.png" },
      { id: 7, word: "mountain", image: "card7.png" },
      ]
    },
    { id: 11, 
      name: "Unit 11 - How's the weather? It's ...", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "sunny", image: "card1.png"},
      { id: 2, word: "cloudy", image: "card2.png" },
      { id: 3, word: "windy", image: "card3.png" },
      { id: 4, word: "rainy", image: "card4.png" },
      { id: 5, word: "snowy", image: "card5.png" },
      { id: 6, word: "stormy", image: "card6.png" },
      { id: 7, word: "typhoon", image: "card7.png" },
      ]
    },
    { id: 12, 
      name: "Unit 12 - Let's learn more.", 
      numFlashcards: 4,
      cards: [
      { id: 1, word: "paddle", image: "card1.png"},
      { id: 2, word: "dragon boat", image: "card2.png" },
      { id: 3, word: "stand an egg", image: "card3.png" },
      { id: 4, word: "rice dumplings", image: "card4.png" },
      ]
    },
    { id: 13, 
      name: "Unit 13 - Put on ...", 
      numFlashcards: 7,
      cards: [
      { id: 1, word: "hat", image: "card1.png"},
      { id: 2, word: "swimming cap", image: "card2.png" },
      { id: 3, word: "swimsuit", image: "card3.png" },
      { id: 4, word: "sunscreen", image: "card4.png" },
      { id: 5, word: "swimming trunks", image: "card5.png" },
      { id: 6, word: "sunglasses", image: "card6.png" },
      { id: 7, word: "goggles", image: "card7.png" },
      ]
    },
    { id: 14, 
      name: "Unit 14 - When is ... ? It's in ..", 
      numFlashcards: 12,
      cards: [
      { id: 1, word: "New Year's Day", image: "card1.png"},
      { id: 2, word: "Lantern Festival", image: "card2.png" },
      { id: 3, word: "Arbor Day", image: "card3.png" },
      { id: 4, word: "Easter", image: "card4.png" },
      { id: 5, word: "Mother's Day", image: "card5.png" },
      { id: 6, word: "Dragon Boat Festival", image: "card6.png" },
      { id: 7, word: "Summer vacation", image: "card7.png" },
      { id: 8, word: "Father's Day", image: "card8.png" },
      { id: 9, word: "Moon Festival", image: "card9.png" },
      { id: 10, word: "Halloween", image: "card10.png" },
      { id: 11, word: "Thanksgiving", image: "card11.png" },
      { id: 12, word: "Christmas", image: "card12.png" },
      ]
    },
    { id: 15, 
      name: "Unit 15 - Where's ... ? It's in ...", 
      numFlashcards: 6,
      cards: [
      { id: 1, word: "Taipei 101", image: "card1.png"},
      { id: 2, word: "London Bridge", image: "card2.png" },
      { id: 3, word: "the Sydney Opera House", image: "card3.png" },
      { id: 4, word: "the Great Wall", image: "card4.png" },
      { id: 5, word: "the Statue of Liberty", image: "card5.png" },
      { id: 6, word: "the Eiffel Tower", image: "card6.png" },
      ]
    },
    { id: 16, 
      name: "Unit 16 - Let's learn more.", 
      numFlashcards: 10,
      cards: [
      { id: 1, word: "short", image: "card1.png"},
      { id: 2, word: "tall", image: "card2.png" },
      { id: 3, word: "naughty", image: "card3.png" },
      { id: 4, word: "good", image: "card4.png" },
      { id: 5, word: "chubby", image: "card5.png" },
      { id: 6, word: "very chubby", image: "card6.png" },
      { id: 7, word: "Don't shout.", image: "card7.png" },
      { id: 8, word: "Don't quarrel.", image: "card8.png" },
      { id: 9, word: "Don't fight.", image: "card9.png" },
      { id: 10, word: "Don't tell a lie.", image: "card10.png" },
      ]
    },
  ];
